### ISSUE TITLE
Redux-Saga dependency 

### ISSUE THREAD

**Issue by mpolichette** [PCreations/redux-paginator#8]
I started trying to use this project but it seems to require redux-saga or else it fails.  Saga seems to be only a dev-dependency in the `package.json` but there is definitely a require with in `sagas.js` file.

I'm just wondering if that should be explicitly placed in either the `dependencies` or atleast `peer dependencies`

The README seems to express that you could use this w/o redux-saga, am I mistaken?

**Comment by videni** [comment]
I also have this problem,   it seems this lib is mot maintained anymore.

**Comment by ClementKerneur** [comment]
I confirm that i have also this problem. I solve this issue into PR #14
